version: '3'

services:
  rinha-postgres:
    container_name: rinha-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - rinha-db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgresql.conf:/etc/postgresql/postgresql.conf
#    command: postgres -c config_file=/etc/postgresql/postgresql.conf
#    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c full_page_writes=0 -c max_connections=50
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2096 -c synchronous_commit=0 -c full_page_writes=0 -c fsync=off -c check_function_bodies=false
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: '30MB'

  api01: &api
    image: claudio2424/rinha-spring:native
    hostname: api01
    ports:
      - "6969:6969"
    depends_on:
      - rinha-postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "175MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "9696:6969"

#  pgAdmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      # PGADMIN_LISTEN_PORT: 5050
#    ports:
#      - "5050:80"
#    depends_on:
#      - rinha-postgres

volumes:
  rinha-db: