version: '3'

services:
  rinha-postgres:
    container_name: rinha-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
      DATABASES_POOL_SIZE: 20
    ports:
      - "5432:5432"
    volumes:
      - rinha-db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c log_min_messages=FATAL
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

  api01: &api
    image: claudio2424/rinha-spring:1.2
    hostname: api01
    ports:
      - "6969:6969"
    depends_on:
      - rinha-postgres
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "550MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "9696:6969"

networks:
  rinha-network:
    driver: host

volumes:
  rinha-db:
